apiVersion: v1
kind: ServiceAccount
metadata:
  name: tutorial-service-account
---
apiVersion: v1
kind: Secret
metadata:
  name: tutorial-service-account
  annotations:
    kubernetes.io/service-account.name: tutorial-service-account
type: kubernetes.io/service-account-token
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tutorial-role
rules:
- apiGroups:
  - '*'
  resources:
  - "*"
  verbs:
  - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tutorial-role-binding
subjects:
  - kind: ServiceAccount
    name: tutorial-service-account
    namespace: participant-<id>
roleRef:
  kind: Role
  name: tutorial-role
  apiGroup: rbac.authorization.k8s.io
